import { jsonb, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { idColumn } from "./common";
import { user } from "./user";

/**
 * Chat-scoped activity log for the dashboard AI operator panel
 * (/admin → AgentChatPanel → /api/admin/agent/chat).
 *
 * This is separate from the platform's append-only `audit_log` (which
 * records the business consequences of actions, e.g. an application being
 * approved). This table records the *conversation-level* tool activity:
 * every tool the chat agent executes and every approval decision the owner
 * makes on an approval-gated tool, with the arguments and a short result
 * summary. The business mutation itself is still audited through the
 * normal path (decideApplication / publishCatalogImport → audit_log).
 *
 * Unlike audit_log, this table is a chat transcript aid, not a compliance
 * record — but it is still insert-only by convention: no code path updates
 * or deletes rows here.
 */
export const agentAuditLog = pgTable("agent_audit_log", {
  id: idColumn(),
  actorUserId: uuid("actor_user_id").references(() => user.id),
  actorRole: text("actor_role"),
  /** Which tool ran, e.g. "list_applications" or "approve_application". */
  tool: text("tool").notNull(),
  /** The arguments the model passed to the tool (validated input). */
  arguments: jsonb("arguments").notNull(),
  /**
   * For approval-gated tools: "requested" (tool asked for approval),
   * "granted" (owner approved and it executed), "denied" (owner declined).
   * For read tools this is always "executed".
   */
  approvalDecision: text("approval_decision").notNull().default("executed"),
  /** Short human-readable summary of what the tool returned/did. */
  resultSummary: text("result_summary"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const agentSuggestionKind = pgEnum("agent_suggestion_kind", [
  "margin_alert",
  "restock_idea",
  "market_brief",
  "ops_nudge",
]);

/**
 * Proactive suggestions generated by the daily /api/cron/agent-suggestions
 * job (rule-based queries over orders/catalog/applications — no LLM in the
 * cron). The chat panel surfaces the latest rows when it opens and whenever
 * the owner asks "what's new". Rows are never updated; a suggestion is
 * superseded by a newer row of the same kind+dedupeKey.
 */
export const agentSuggestion = pgTable("agent_suggestion", {
  id: idColumn(),
  kind: agentSuggestionKind("kind").notNull(),
  title: text("title").notNull(),
  body: text("body").notNull(),
  /** Stable key for dedupe, e.g. "margin:product:<id>" or "brief:2026-W38". */
  dedupeKey: text("dedupe_key").notNull(),
  payload: jsonb("payload"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
